"""
Telegram Bot Provider for ConnectorHub.
Loads and registers actions from the centralized 'actions_catalog.json'.
Aligned with the official Telegram Bot API specifications.
"""
from typing import Dict, Any, Optional
import httpx

from app.providers.base import Provider, Action
from app.providers.catalog import get_provider_actions
from app.core.ssrf import assert_public_url, execute_guarded_request

TELEGRAM_API_BASE = "https://api.telegram.org"

def _extract_token(credential: Optional[Dict[str, Any]]) -> str:
    token = (credential or {}).get("apiKey") or (credential or {}).get("accessToken") or (credential or {}).get("botToken")
    if not token or not str(token).strip():
        raise ValueError("Telegram Bot Token required (format: 123456789:AA...). Please connect your Telegram Bot first.")
    return str(token).strip()

def _to_camel_case(snake_str: str) -> str:
    components = snake_str.split("_")
    return components[0] + "".join(x.capitalize() for x in components[1:])

class TelegramDynamicAction(Action):
    def __init__(self, action_meta: Dict[str, Any]):
        super().__init__(
            id=action_meta["id"],
            name=action_meta["name"],
            description=action_meta["description"],
            category=action_meta.get("category", "General"),
            required_scopes=action_meta.get("required_scopes", []),
            input_schema=action_meta.get("input_schema", {"type": "object", "properties": {}})
        )
        # Extract telegram method: e.g. 'telegram.send_message' -> 'sendMessage'
        action_name = action_meta["id"].split(".")[-1]
        self.telegram_method = _to_camel_case(action_name)

    async def execute(self, input_data: Dict[str, Any], credential: Optional[Dict[str, Any]], client: httpx.AsyncClient) -> Dict[str, Any]:
        token = _extract_token(credential)
        inputs = dict(input_data or {})

        url = f"{TELEGRAM_API_BASE}/bot{token}/{self.telegram_method}"
        assert_public_url(url)

        resp = await execute_guarded_request(
            client=client,
            method="POST",
            url=url,
            json_body=inputs if inputs else None
        )

        if resp.status_code >= 400:
            err_text = resp.text
            try:
                err_json = resp.json()
                msg = err_json.get("description") or str(err_json)
            except Exception:
                msg = err_text[:300]
            raise ValueError(f"Telegram Bot API error ({resp.status_code}): {msg}")

        data = resp.json()
        if not data.get("ok"):
            raise ValueError(f"Telegram API rejected request: {data.get('description', 'Unknown error')}")

        return data.get("result", data)

class TelegramProvider(Provider):
    def __init__(self):
        super().__init__(
            service="telegram",
            display_name="Telegram Bot",
            category="Communication",
            auth_types=["api_key"],
            description="Telegram Bot API for sending messages, photos, documents, inline queries, and managing groups and channels.",
            homepage_url="https://core.telegram.org/bots",
            base_url=TELEGRAM_API_BASE,
            auth_configs=[
                {
                    "type": "api_key",
                    "label": "Telegram Bot Token",
                    "placeholder": "123456789:ABCdefGHIjklMNOpqrsTUVwxyz...",
                    "description": "Bot API token generated by @BotFather on Telegram.",
                    "docs_url": "https://core.telegram.org/bots/features#botfather",
                    "docs_label": "Telegram BotFather Documentation",
                    "setup_guide": {
                        "title": "Telegram Bot Token Setup Guide",
                        "docs_url": "https://core.telegram.org/bots/features#botfather",
                        "docs_label": "BotFather Guide",
                        "instructions": [
                            "1. Open Telegram and search for the verified '@BotFather' account.",
                            "2. Send the message '/newbot' to create a new bot.",
                            "3. Follow the prompts to set a display name and unique username ending in 'bot'.",
                            "4. Copy the HTTP API token provided by BotFather (format: 123456789:AA...)."
                        ],
                        "scopes": []
                    },
                    "fields": [
                        {
                            "key": "apiKey",
                            "label": "Bot Token",
                            "type": "password",
                            "required": True,
                            "placeholder": "123456789:AA...",
                            "description": "Telegram Bot API token provided by @BotFather."
                        }
                    ]
                }
            ]
        )

        for meta in get_provider_actions("telegram"):
            self.register_action(TelegramDynamicAction(meta))

    async def validate_credentials(self, credential: Dict[str, Any], client: httpx.AsyncClient) -> Dict[str, Any]:
        """Validate credentials against Telegram Bot API getMe."""
        token = _extract_token(credential)
        url = f"{TELEGRAM_API_BASE}/bot{token}/getMe"
        assert_public_url(url)

        try:
            resp = await execute_guarded_request(
                client=client,
                method="GET",
                url=url
            )
        except Exception as e:
            raise ValueError(f"Unable to reach Telegram API: {str(e)}")

        if resp.status_code == 401 or resp.status_code == 404:
            raise ValueError("Invalid Telegram Bot token. Telegram API returned 401/404.")
        elif resp.status_code != 200:
            raise ValueError(f"Telegram validation failed with status {resp.status_code}: {resp.text[:300]}")

        data = resp.json()
        if not data.get("ok"):
            raise ValueError(f"Telegram API rejected token: {data.get('description', 'Unauthorized')}")

        bot_info = data.get("result", {})
        bot_id = str(bot_info.get("id") or "telegram_bot")
        bot_username = bot_info.get("username") or bot_info.get("first_name") or bot_id

        return {
            "account_id": bot_id,
            "display_name": f"Telegram (@{bot_username})",
            "granted_scopes": [],
            "avatar_url": None
        }

    async def proxy(
        self,
        endpoint: str,
        method: str,
        credential: Optional[Dict[str, Any]],
        body: Any,
        headers: Dict[str, str],
        client: httpx.AsyncClient
    ) -> Dict[str, Any]:
        """SSRF-guarded proxy forwarder for Telegram Bot API."""
        token = _extract_token(credential)
        clean_endpoint = endpoint.lstrip("/")
        target_url = f"{TELEGRAM_API_BASE}/bot{token}/{clean_endpoint}"
        assert_public_url(target_url)

        resp = await execute_guarded_request(
            client=client,
            method=method.upper(),
            url=target_url,
            headers=dict(headers or {}),
            json_body=body if body and method.upper() in ["POST", "PUT", "PATCH"] else None
        )

        try:
            resp_data = resp.json()
        except Exception:
            resp_data = resp.text

        return {
            "status": resp.status_code,
            "headers": dict(resp.headers),
            "data": resp_data
        }
